---
name: "Deploying the docker compose"

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  Ansible:
    name: "Installing docker and docker compose plugin in the server"
    runs-on: ubuntu-latest

    steps:
      - name: "Checking out the repository"
        uses: actions/checkout@v4

      - name: "Installing ansible"
        run: sudo apt-get update -y && sudo apt-get install -y ansible

      - name: "Setup SSH Ansible"
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: "Running the playbook"
        run: ansible-playbook -i ${{secrets.SSH_HOST}} setup-server.yaml

  web-server:
    name: "Running the container application"
    needs: [Ansible]
    runs-on: ubuntu-latest

    steps:
      - name: "Checking out the repository"
        uses: actions/checkout@v4

      - name: "Docker login"
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Set up Qemu
        uses: docker/setup-qemu-action@v3

      - name: Set up DockerBuildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: abirthapa1/todo-list-backend:${{github.sha}}

      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: abirthapa1/todo-list-frontend:${{github.sha}}

      - name: "SSHing and runniong the compose file"
        uses: appleboy/ssh-action@v1
        with:
          host: ${{secrets.SSH_HOST}}
          username: ec2-user
          key: ${{secrets.SSH_KEY}}
          script: |
            curl -fsSL https://raw.githubusercontent.com/abirthapa1/Multi-container-application/refs/heads/main/docker-compose.yaml -O docker-compose.yaml
            docker-compose up -d --build
