---
name: "deploying the docker file"

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  web-server:
    name: "Running the container application"
    runs-on: ubuntu-latest

    steps:
      - name: "Checking out the repository"
        uses: actions/checkout@v4

      - name: "Docker login"
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USER}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      - name: Set up Qemu
        uses: docker/setup-qemu-action@v3

      - name: Set up DockerBuildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: abirthapa1/todo-list-frontend:latest
